resolver: lts-12.0

packages:
- '.'
- location:
    git: https://github.com/xmonad/xmonad
    commit: bb13853929f8f6fc59b526bcc10631e1bac309ad
  extra-dep: true
- location:
    git: https://github.com/xmonad/xmonad-contrib
    commit: dda242a4597c1ed0fa895a10b9296dcc709f4937
  extra-dep: true
- location:
    git: https://github.com/taffybar/taffybar
    commit: bb275b4fcbd02207b81c2e8265bfe4f5edafc387 
  extra-dep: true
extra-deps: 
  - X11-xft-0.3.1
  - dbus-1.0.1
  - dbus-hslogger-0.1.0.1
  - gi-dbusmenu-0.4.1
  - gi-dbusmenugtk3-0.4.1
  - gi-gdk-3.0.15
  - gi-gdkpixbuf-2.0.16
  - gi-gdkx11-3.0.2
  - gi-gio-2.0.16
  - gi-gtk-3.0.21
  - gi-gtk-hs-0.3.6.1
  - gi-pango-1.0.16
  - gi-xlib-2.0.2
  - gio-0.13.4.1
  - gtk-sni-tray-0.1.4.0
  - gtk-strut-0.1.2.1
  - haskell-gi-0.21.2
  - haskell-gi-base-0.21.1
  - libxml-sax-0.7.5
  - rate-limit-1.1.1
  - spool-0.1
  - status-notifier-item-0.3.0.0
  - time-units-1.0.0
  - xml-helpers-1.0.0
  # - binary-0.9.0.0
  - containers-0.5.11.0
  - template-haskell-2.13.0.0
  - transformers-0.5.5.0

flags: 
