resolver: lts-11.7

packages:
- '.'
# - location: './xmonad-git'
#   extra-dep: true
# - location: 'xmonad-contrib-git'
#   extra-dep: true
- location:
    git: https://github.com/xmonad/xmonad
    commit: 76f4a162587a8c6b58afe3d76341336cfe3c9aa3
  extra-dep: true
- location:
    git: https://github.com/xmonad/xmonad-contrib
    commit: ca9b7d9dfcaf972152731420fe9f1ef01d967f5d
  extra-dep: true
- location:
    git: https://github.com/taffybar/taffybar
    commit: a6a2ce22f081b38bc375ffbe040852680c5a97e4
  extra-dep: true
extra-deps: 
  - X11-xft-0.3.1
  - dbus-1.0.1
  - dbus-hslogger-0.1.0.1
  - gi-dbusmenu-0.4.1
  - gi-dbusmenugtk3-0.4.1
  - gi-gdk-3.0.15
  - gi-gdkpixbuf-2.0.16
  - gi-gdkx11-3.0.2
  - gi-gio-2.0.16
  - gi-gtk-3.0.21
  - gi-pango-1.0.16
  - gi-xlib-2.0.2
  - gio-0.13.4.1
  - gtk-sni-tray-0.1.2.0
  - gtk-strut-0.1.2.0
  - gtk-traymanager-1.0.1
  - gtk3-0.14.9
  - haskell-gi-0.21.2
  - haskell-gi-base-0.21.1
  - libxml-sax-0.7.5
  - rate-limit-1.1.1
  - spool-0.1
  - status-notifier-item-0.2.1.0
  - time-units-1.0.0
  - xml-helpers-1.0.0

flags: 
