packages:
- '.'
- location: './taffybar'
  extra-dep: true
- location:
    git: https://github.com/willdonnelly/dyre
    commit: 11412752b483135e0c151ab90be17b217f837c4b
  extra-dep: true
- location:
    git: https://github.com/IvanMalison/gtk2hs.git
    commit: 6e2b94f62d94ff9c7e80546b884be48ab77c46bf
  extra-dep: true
  subdirs:
      - gtk
extra-deps:
- X11-xft-0.3.1
- dbus-1.0.1
- gi-dbusmenu-0.4.1
- gi-dbusmenugtk3-0.4.1
- gi-gdk-3.0.15
- gi-gdkpixbuf-2.0.15
- gi-gdkx11-3.0.2
- gi-gio-2.0.16
- gi-gtk-3.0.21
- gi-pango-1.0.16
- gi-xlib-2.0.2
- gio-0.13.4.1
- gtk-strut-0.1.2.0
- gtk-traymanager-1.0.1
- libxml-sax-0.7.5
- rate-limit-1.1.1
- spool-0.1
- time-units-1.0.0
- xml-helpers-1.0.0
- haskell-gi-0.21.2
- haskell-gi-base-0.21.1

resolver: lts-11.4
