#!/bin/sh

LOG_FILE=~/.local/logs/bspwm/run.log

mkdir -p `dirname $LOG_FILE`
touch $LOG_FILE

echo Start bspwm `date` >> $LOG_FILE

_log()
{
  echo $1 >> $LOG_FILE 
}

_inc()
{
  echo $(($1+1))
}

sxhkd &

# Test if numlockx is installed
if type numlockx > /dev/null; then
  numlockx on
fi

# bspc monitor -d I II III IV V VI VII VIII IX X

i=1
for m in $(bspc query -M | head -n -1); do
  bspc monitor $m \
    -n "$1" \
    -d $i
  i=$(_inc $i)
done

last_monitor=$(bspc query -M | tail -1)

bspc monitor $last_monitor -d $(seq $i 10)

bspc config border_width         3
bspc config window_gap           2 

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

wmname LG3D

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
