#!/usr/bin/env sh

set -e

wkhtmltopdf -n -g -s a5 "$1" "/tmp/$2"

echo "`date` Start upload of $1 ($2)" >> /tmp/remarkable.log

rmapi put "/tmp/$2"

echo "`date` Finished upload of $1 ($2)" >> /tmp/remarkable.log

notify-send "Download Complete" "$2"
