#!/usr/bin/env sh

set -e

SANITIZED_NAME=`echo $2 | sed -E 's#/#\\\\#p'`

wkhtmltopdf -n -g -s a5 "$1" "/tmp/$SANITIZED_NAME"

echo "`date` Start upload of $1 ($SANITIZED_NAME)" >> /tmp/remarkable.log

rmapi put "/tmp/$SANITIZED_NAME"

echo "`date` Finished upload of $1 ($SANITIZED_NAME)" >> /tmp/remarkable.log

notify-send "Download Complete" "$SANITIZED_NAME"
