#!/usr/bin/env bash
#
# Behavior:
#   Userscript for qutebrowser which views the current web page in mpv using
#   sensible mpv-flags. While viewing the page in MPV, all <video>, <embed>,
#   and <object> tags in the original page are temporarily removed. Clicking on
#   such a removed video restores the respective video.
#
#   In order to use this script, just start it using `spawn --userscript` from
#   qutebrowser. I recommend using an alias, e.g. put this in the
#   [alias]-section of qutebrowser.conf:
#
#     mpv = spawn --userscript /path/to/view_in_mpv
#
# Background:
#   Most of my machines are too slow to play youtube videos using html5, but
#   they work fine in mpv (and mpv has further advantages like video scaling,
#   etc). Of course, I don't want the video to be played (or even to be
#   downloaded) twice — in MPV and in qwebkit. So I often close the tab after
#   opening it in mpv. However, I actually want to keep the rest of the page
#   (comments and video suggestions), i.e. only the videos should disappear
#   when mpv is started. And that's precisely what the present script does.
#
# Thorsten Wißmann, 2015 (thorsten` on freenode)
# Any feedback is welcome!

set -e

if [ -z "$QUTE_FIFO" ] ; then
    cat 1>&2 <<EOF
Error: $0 can not be run as a standalone script.

It is a qutebrowser userscript. In order to use it, call it using
'spawn --userscript' as described in qute://help/userscripts.html
EOF
    exit 1
fi

msg() {
    local cmd="$1"
    shift
    local msg="$*"
    if [ -z "$QUTE_FIFO" ] ; then
        echo "$cmd: $msg" >&2
    else
        echo "message-$cmd '${msg//\'/\\\'}'" >> "$QUTE_FIFO"
    fi
}

MPV_COMMAND=${MPV_COMMAND:-mpv}
# Warning: spaces in single flags are not supported
MPV_FLAGS=${MPV_FLAGS:- --profile=web }
IFS=" " read -r -a video_command <<< "$MPV_COMMAND $MPV_FLAGS"

msg info "Opening $QUTE_URL with mpv"
"${video_command[@]}" "$@" "$QUTE_URL"

